disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace # empty lines having whitespaces
  - line_length # warning 120, error 200

excluded:
  - Carthage
  - Pods

weak_delegate: error
