osx_image: xcode9.3
language: objective-c
cache:
- bundler
- cocoapods

before_install:
  - brew update

script:
  - xcodebuild clean test -quiet -workspace Foursquare.xcworkspace -scheme Foursquare -destination 'platform=iOS Simulator,name=iPhone 5s'
  - bundle exec danger

after_success:
  - bash <(curl -s https://codecov.io/bash)
